/** 事件触发分组 */
export enum EventTriggerGroup {
  /** 问卷 */
  questionnaire = 'questionnaire',
  /** 时间类型 */
  time = 'time',
  /** 组件相关 */
  component = 'component',
  /** 页面相关 */
  page = 'page',
  /** 用户行为相关 */
  action = 'action',
  /** 浏览器行为相关 */
  browser = 'browser',
  /** 系统 */
  system = 'system',
  /** 音视频相关 */
  media = 'media',
}

/** 事件行为分组 */
export enum EventActionGroup {
  /** 问卷 */
  questionnaire = 'questionnaire',
  /** 时间类型 */
  time = 'time',
  /** 组件行为 */
  component = 'component',
  /** 表单分页行为 */
  formPage = 'form-page',
  /** 应用分页行为 */
  page = 'page',
  /** 系统层面行为 */
  system = 'system',
  /** 音视频相关 */
  media = 'media',
}

/** 事件触发类型 */
export enum EventTriggerType {
  /** 控制台触发 */
  console = 'console',
  /** 跳转到答题页 */
  gotoAnswerPage = 'goto-answer-page',
  /** 跳转到起始页 */
  gotoStartPage = 'goto-start-page',
  /** 跳转到完成页 */
  gotoEndPage = 'goto-end-page',
  /** 定时器 */
  timer = 'timer',
  /** 开始记时 */
  timeStart = 'timing-start',
  /** 暂停记时 */
  timePause = 'timing-pause',
  /** 显示题（翻页带来的显示） */
  showComponent = 'show',
  /** 隐藏题（翻页带来的隐藏） */
  hideComponent = 'hide',
  /** 值 */
  valueChange = 'valueChange',
  /** 点击 */
  click = 'click',
  /** 上一题 */
  prevComponent = 'prev-component',
  /** 下一题 */
  nextComponent = 'next-component',
  /** 跳转 */
  gotoComponent = 'goto-component',
  /** 上一表单页（内部页） */
  prevFormPage = 'prev-form-page',
  /** 下一表单页（内部页） */
  nextFormPage = 'next-form-page',
  /** 跳转表单页（内部页） */
  gotoFormPage = 'goto-form-page',
  /** 上一应用页 */
  prevPage = 'prev-page',
  /** 上一应用页 */
  nextPage = 'next-page',
  /** 跳转应用页 */
  gotoPage = 'goto-page',
  /** 提交表单前 */
  beforeSubmitForm = 'before-submit-form',
  /** 提交表单 */
  submitForm = 'submit-form',
  /** 终止表单 */
  abortForm = 'abort-form',
  /** 重置表单 */
  resetForm = 'reset-form',
  /** 开始播放 */
  startPlay = 'start-play',
  /** 暂停播放 */
  pausePlay = 'pause-play',
  /** 停止播放 */
  stopPlay = 'stop-play',
  /** 加载数据中 */
  loadingWaiting = 'loading-waiting',
  /** 加载完播放 */
  loadingComplete = 'loading-complete',
  /** 应用加载完毕 */
  appInit = 'app-init',
  /** 应用加载完毕 */
  appLoadingComplete = 'app-loading-complete',
  /** 应用显示 */
  appShow = 'appShow',
  /** 应用隐藏 */
  appHide = 'appHide',
}

/** 事件行为类型 */
export enum AppEventActionType {
  /** 显示当前题 */
  show = 'show',
  /** 隐藏当前题 */
  hide = 'hide',
  /** 跳转到某题 */
  turn = 'turn',
  /** 改变值 */
  setValue = 'setValue',
  /** 下一题 */
  next = 'next',
  /** 上一题 */
  prev = 'prev',
}
