import {
  AppstoreOutlined,
  ProfileOutlined,
  DeleteOutlined,
  ToolOutlined,
  MinusCircleOutlined,
  PlusCircleOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  CopyOutlined,
  ThunderboltOutlined,
  SettingOutlined,
  DownOutlined,
  ShakeOutlined,
  LaptopOutlined,
  QuestionCircleOutlined,
  PlusOutlined,
  EditOutlined,
  AimOutlined,
  SendOutlined,
  FileOutlined,
  EyeOutlined,
  SkinOutlined,
  CheckOutlined,
  ExportOutlined,
  ScanOutlined,
  SaveOutlined,
  DeleteFilled,
  SelectOutlined,
  FormOutlined,
  ContainerOutlined,
  QrcodeOutlined,
  VerticalAlignBottomOutlined,
  SearchOutlined,
  HomeOutlined,
  UserOutlined,
  LockOutlined,
  BgColorsOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  BorderOutlined,
  CheckSquareFilled,
  CloseOutlined,
  WarningOutlined,
  FunctionOutlined,
  ClearOutlined,
} from '@ant-design/icons-vue';
import { App } from 'vue';

const icons = {
  AppstoreOutlined,
  ProfileOutlined,
  DeleteOutlined,
  ToolOutlined,
  MinusCircleOutlined,
  PlusCircleOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  CopyOutlined,
  ThunderboltOutlined,
  SettingOutlined,
  DownOutlined,
  ShakeOutlined,
  LaptopOutlined,
  QuestionCircleOutlined,
  PlusOutlined,
  EditOutlined,
  AimOutlined,
  SendOutlined,
  FileOutlined,
  EyeOutlined,
  SkinOutlined,
  CheckOutlined,
  ExportOutlined,
  ScanOutlined,
  SaveOutlined,
  DeleteFilled,
  SelectOutlined,
  FormOutlined,
  ContainerOutlined,
  QrcodeOutlined,
  VerticalAlignBottomOutlined,
  SearchOutlined,
  HomeOutlined,
  UserOutlined,
  LockOutlined,
  BgColorsOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  BorderOutlined,
  CheckSquareFilled,
  CloseOutlined,
  WarningOutlined,
  FunctionOutlined,
  ClearOutlined,
};

export default {
  install(app: App) {
    Object.entries(icons).forEach(([key, value]) => {
      app.component(key, value);
    });
  },
};
